// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAuth = `-- name: GetAuth :one
SELECT athlete_id, access_token, refresh_token, expires_at
FROM auth
WHERE id = 1
`

type GetAuthRow struct {
	AthleteID    int64  `db:"athlete_id"`
	AccessToken  string `db:"access_token"`
	RefreshToken string `db:"refresh_token"`
	ExpiresAt    int64  `db:"expires_at"`
}

func (q *Queries) GetAuth(ctx context.Context) (GetAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getAuth)
	var i GetAuthRow
	err := row.Scan(
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
	)
	return i, err
}

const saveAuth = `-- name: SaveAuth :exec
INSERT INTO auth (id, athlete_id, access_token, refresh_token, expires_at, updated_at)
VALUES (1, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    athlete_id = excluded.athlete_id,
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    expires_at = excluded.expires_at,
    updated_at = CURRENT_TIMESTAMP
`

type SaveAuthParams struct {
	AthleteID    int64  `db:"athlete_id"`
	AccessToken  string `db:"access_token"`
	RefreshToken string `db:"refresh_token"`
	ExpiresAt    int64  `db:"expires_at"`
}

func (q *Queries) SaveAuth(ctx context.Context, arg SaveAuthParams) error {
	_, err := q.db.ExecContext(ctx, saveAuth,
		arg.AthleteID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}

const updateTokens = `-- name: UpdateTokens :execresult
UPDATE auth
SET access_token = ?, refresh_token = ?, expires_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateTokensParams struct {
	AccessToken  string `db:"access_token"`
	RefreshToken string `db:"refresh_token"`
	ExpiresAt    int64  `db:"expires_at"`
}

func (q *Queries) UpdateTokens(ctx context.Context, arg UpdateTokensParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTokens, arg.AccessToken, arg.RefreshToken, arg.ExpiresAt)
}
