// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: metrics.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countMetrics = `-- name: CountMetrics :one
SELECT COUNT(*) FROM activity_metrics
`

func (q *Queries) CountMetrics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMetrics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivitiesWithMetricsRaw = `-- name: GetActivitiesWithMetricsRaw :many
SELECT a.id, a.athlete_id, a.name, a.type, a.start_date, a.start_date_local, a.timezone,
    a.distance, a.moving_time, a.elapsed_time, a.total_elevation_gain,
    a.average_speed, a.max_speed, a.average_heartrate, a.max_heartrate,
    a.average_cadence, a.suffer_score, a.has_heartrate, a.streams_synced,
    m.efficiency_factor, m.aerobic_decoupling, m.cardiac_drift,
    m.pace_at_z1, m.pace_at_z2, m.pace_at_z3, m.trimp, m.hrss,
    m.data_quality_score, m.steady_state_pct
FROM activities a
JOIN activity_metrics m ON a.id = m.activity_id
ORDER BY a.start_date DESC
LIMIT ? OFFSET ?
`

type GetActivitiesWithMetricsRawParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

type GetActivitiesWithMetricsRawRow struct {
	ID                 int64           `db:"id"`
	AthleteID          int64           `db:"athlete_id"`
	Name               string          `db:"name"`
	Type               string          `db:"type"`
	StartDate          string          `db:"start_date"`
	StartDateLocal     string          `db:"start_date_local"`
	Timezone           sql.NullString  `db:"timezone"`
	Distance           float64         `db:"distance"`
	MovingTime         int64           `db:"moving_time"`
	ElapsedTime        int64           `db:"elapsed_time"`
	TotalElevationGain sql.NullFloat64 `db:"total_elevation_gain"`
	AverageSpeed       sql.NullFloat64 `db:"average_speed"`
	MaxSpeed           sql.NullFloat64 `db:"max_speed"`
	AverageHeartrate   sql.NullFloat64 `db:"average_heartrate"`
	MaxHeartrate       sql.NullFloat64 `db:"max_heartrate"`
	AverageCadence     sql.NullFloat64 `db:"average_cadence"`
	SufferScore        sql.NullInt64   `db:"suffer_score"`
	HasHeartrate       int64           `db:"has_heartrate"`
	StreamsSynced      int64           `db:"streams_synced"`
	EfficiencyFactor   sql.NullFloat64 `db:"efficiency_factor"`
	AerobicDecoupling  sql.NullFloat64 `db:"aerobic_decoupling"`
	CardiacDrift       sql.NullFloat64 `db:"cardiac_drift"`
	PaceAtZ1           sql.NullFloat64 `db:"pace_at_z1"`
	PaceAtZ2           sql.NullFloat64 `db:"pace_at_z2"`
	PaceAtZ3           sql.NullFloat64 `db:"pace_at_z3"`
	Trimp              sql.NullFloat64 `db:"trimp"`
	Hrss               sql.NullFloat64 `db:"hrss"`
	DataQualityScore   sql.NullFloat64 `db:"data_quality_score"`
	SteadyStatePct     sql.NullFloat64 `db:"steady_state_pct"`
}

func (q *Queries) GetActivitiesWithMetricsRaw(ctx context.Context, arg GetActivitiesWithMetricsRawParams) ([]GetActivitiesWithMetricsRawRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivitiesWithMetricsRaw, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivitiesWithMetricsRawRow{}
	for rows.Next() {
		var i GetActivitiesWithMetricsRawRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.Name,
			&i.Type,
			&i.StartDate,
			&i.StartDateLocal,
			&i.Timezone,
			&i.Distance,
			&i.MovingTime,
			&i.ElapsedTime,
			&i.TotalElevationGain,
			&i.AverageSpeed,
			&i.MaxSpeed,
			&i.AverageHeartrate,
			&i.MaxHeartrate,
			&i.AverageCadence,
			&i.SufferScore,
			&i.HasHeartrate,
			&i.StreamsSynced,
			&i.EfficiencyFactor,
			&i.AerobicDecoupling,
			&i.CardiacDrift,
			&i.PaceAtZ1,
			&i.PaceAtZ2,
			&i.PaceAtZ3,
			&i.Trimp,
			&i.Hrss,
			&i.DataQualityScore,
			&i.SteadyStatePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityMetrics = `-- name: GetActivityMetrics :one
SELECT activity_id, efficiency_factor, aerobic_decoupling, cardiac_drift,
    pace_at_z1, pace_at_z2, pace_at_z3, trimp, hrss,
    data_quality_score, steady_state_pct
FROM activity_metrics
WHERE activity_id = ?
`

type GetActivityMetricsRow struct {
	ActivityID        int64           `db:"activity_id"`
	EfficiencyFactor  sql.NullFloat64 `db:"efficiency_factor"`
	AerobicDecoupling sql.NullFloat64 `db:"aerobic_decoupling"`
	CardiacDrift      sql.NullFloat64 `db:"cardiac_drift"`
	PaceAtZ1          sql.NullFloat64 `db:"pace_at_z1"`
	PaceAtZ2          sql.NullFloat64 `db:"pace_at_z2"`
	PaceAtZ3          sql.NullFloat64 `db:"pace_at_z3"`
	Trimp             sql.NullFloat64 `db:"trimp"`
	Hrss              sql.NullFloat64 `db:"hrss"`
	DataQualityScore  sql.NullFloat64 `db:"data_quality_score"`
	SteadyStatePct    sql.NullFloat64 `db:"steady_state_pct"`
}

func (q *Queries) GetActivityMetrics(ctx context.Context, activityID int64) (GetActivityMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getActivityMetrics, activityID)
	var i GetActivityMetricsRow
	err := row.Scan(
		&i.ActivityID,
		&i.EfficiencyFactor,
		&i.AerobicDecoupling,
		&i.CardiacDrift,
		&i.PaceAtZ1,
		&i.PaceAtZ2,
		&i.PaceAtZ3,
		&i.Trimp,
		&i.Hrss,
		&i.DataQualityScore,
		&i.SteadyStatePct,
	)
	return i, err
}

const getAllMetrics = `-- name: GetAllMetrics :many
SELECT m.activity_id, m.efficiency_factor, m.aerobic_decoupling, m.cardiac_drift,
    m.pace_at_z1, m.pace_at_z2, m.pace_at_z3, m.trimp, m.hrss,
    m.data_quality_score, m.steady_state_pct
FROM activity_metrics m
JOIN activities a ON m.activity_id = a.id
ORDER BY a.start_date DESC
`

type GetAllMetricsRow struct {
	ActivityID        int64           `db:"activity_id"`
	EfficiencyFactor  sql.NullFloat64 `db:"efficiency_factor"`
	AerobicDecoupling sql.NullFloat64 `db:"aerobic_decoupling"`
	CardiacDrift      sql.NullFloat64 `db:"cardiac_drift"`
	PaceAtZ1          sql.NullFloat64 `db:"pace_at_z1"`
	PaceAtZ2          sql.NullFloat64 `db:"pace_at_z2"`
	PaceAtZ3          sql.NullFloat64 `db:"pace_at_z3"`
	Trimp             sql.NullFloat64 `db:"trimp"`
	Hrss              sql.NullFloat64 `db:"hrss"`
	DataQualityScore  sql.NullFloat64 `db:"data_quality_score"`
	SteadyStatePct    sql.NullFloat64 `db:"steady_state_pct"`
}

func (q *Queries) GetAllMetrics(ctx context.Context) ([]GetAllMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllMetricsRow{}
	for rows.Next() {
		var i GetAllMetricsRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.EfficiencyFactor,
			&i.AerobicDecoupling,
			&i.CardiacDrift,
			&i.PaceAtZ1,
			&i.PaceAtZ2,
			&i.PaceAtZ3,
			&i.Trimp,
			&i.Hrss,
			&i.DataQualityScore,
			&i.SteadyStatePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasMetrics = `-- name: HasMetrics :one
SELECT 1 FROM activity_metrics WHERE activity_id = ? LIMIT 1
`

func (q *Queries) HasMetrics(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasMetrics, activityID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveActivityMetrics = `-- name: SaveActivityMetrics :exec
INSERT INTO activity_metrics (
    activity_id, efficiency_factor, aerobic_decoupling, cardiac_drift,
    pace_at_z1, pace_at_z2, pace_at_z3, trimp, hrss,
    data_quality_score, steady_state_pct, computed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(activity_id) DO UPDATE SET
    efficiency_factor = excluded.efficiency_factor,
    aerobic_decoupling = excluded.aerobic_decoupling,
    cardiac_drift = excluded.cardiac_drift,
    pace_at_z1 = excluded.pace_at_z1,
    pace_at_z2 = excluded.pace_at_z2,
    pace_at_z3 = excluded.pace_at_z3,
    trimp = excluded.trimp,
    hrss = excluded.hrss,
    data_quality_score = excluded.data_quality_score,
    steady_state_pct = excluded.steady_state_pct,
    computed_at = CURRENT_TIMESTAMP
`

type SaveActivityMetricsParams struct {
	ActivityID        int64           `db:"activity_id"`
	EfficiencyFactor  sql.NullFloat64 `db:"efficiency_factor"`
	AerobicDecoupling sql.NullFloat64 `db:"aerobic_decoupling"`
	CardiacDrift      sql.NullFloat64 `db:"cardiac_drift"`
	PaceAtZ1          sql.NullFloat64 `db:"pace_at_z1"`
	PaceAtZ2          sql.NullFloat64 `db:"pace_at_z2"`
	PaceAtZ3          sql.NullFloat64 `db:"pace_at_z3"`
	Trimp             sql.NullFloat64 `db:"trimp"`
	Hrss              sql.NullFloat64 `db:"hrss"`
	DataQualityScore  sql.NullFloat64 `db:"data_quality_score"`
	SteadyStatePct    sql.NullFloat64 `db:"steady_state_pct"`
}

func (q *Queries) SaveActivityMetrics(ctx context.Context, arg SaveActivityMetricsParams) error {
	_, err := q.db.ExecContext(ctx, saveActivityMetrics,
		arg.ActivityID,
		arg.EfficiencyFactor,
		arg.AerobicDecoupling,
		arg.CardiacDrift,
		arg.PaceAtZ1,
		arg.PaceAtZ2,
		arg.PaceAtZ3,
		arg.Trimp,
		arg.Hrss,
		arg.DataQualityScore,
		arg.SteadyStatePct,
	)
	return err
}
