// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Activity struct {
	ID                 int64           `db:"id"`
	AthleteID          int64           `db:"athlete_id"`
	Name               string          `db:"name"`
	Type               string          `db:"type"`
	StartDate          string          `db:"start_date"`
	StartDateLocal     string          `db:"start_date_local"`
	Timezone           sql.NullString  `db:"timezone"`
	Distance           float64         `db:"distance"`
	MovingTime         int64           `db:"moving_time"`
	ElapsedTime        int64           `db:"elapsed_time"`
	TotalElevationGain sql.NullFloat64 `db:"total_elevation_gain"`
	AverageSpeed       sql.NullFloat64 `db:"average_speed"`
	MaxSpeed           sql.NullFloat64 `db:"max_speed"`
	AverageHeartrate   sql.NullFloat64 `db:"average_heartrate"`
	MaxHeartrate       sql.NullFloat64 `db:"max_heartrate"`
	AverageCadence     sql.NullFloat64 `db:"average_cadence"`
	SufferScore        sql.NullInt64   `db:"suffer_score"`
	HasHeartrate       int64           `db:"has_heartrate"`
	StreamsSynced      int64           `db:"streams_synced"`
	CreatedAt          sql.NullString  `db:"created_at"`
	UpdatedAt          sql.NullString  `db:"updated_at"`
}

type ActivityMetric struct {
	ActivityID        int64           `db:"activity_id"`
	EfficiencyFactor  sql.NullFloat64 `db:"efficiency_factor"`
	AerobicDecoupling sql.NullFloat64 `db:"aerobic_decoupling"`
	CardiacDrift      sql.NullFloat64 `db:"cardiac_drift"`
	PaceAtZ1          sql.NullFloat64 `db:"pace_at_z1"`
	PaceAtZ2          sql.NullFloat64 `db:"pace_at_z2"`
	PaceAtZ3          sql.NullFloat64 `db:"pace_at_z3"`
	Trimp             sql.NullFloat64 `db:"trimp"`
	Hrss              sql.NullFloat64 `db:"hrss"`
	DataQualityScore  sql.NullFloat64 `db:"data_quality_score"`
	SteadyStatePct    sql.NullFloat64 `db:"steady_state_pct"`
	ComputedAt        sql.NullString  `db:"computed_at"`
}

type Auth struct {
	ID           int64          `db:"id"`
	AthleteID    int64          `db:"athlete_id"`
	AccessToken  string         `db:"access_token"`
	RefreshToken string         `db:"refresh_token"`
	ExpiresAt    int64          `db:"expires_at"`
	CreatedAt    sql.NullString `db:"created_at"`
	UpdatedAt    sql.NullString `db:"updated_at"`
}

type FitnessTrend struct {
	Date                string          `db:"date"`
	Ctl                 sql.NullFloat64 `db:"ctl"`
	Atl                 sql.NullFloat64 `db:"atl"`
	Tsb                 sql.NullFloat64 `db:"tsb"`
	EfficiencyFactor7d  sql.NullFloat64 `db:"efficiency_factor_7d"`
	EfficiencyFactor28d sql.NullFloat64 `db:"efficiency_factor_28d"`
	EfficiencyFactor90d sql.NullFloat64 `db:"efficiency_factor_90d"`
	RunCount7d          sql.NullInt64   `db:"run_count_7d"`
	TotalDistance7d     sql.NullFloat64 `db:"total_distance_7d"`
	TotalTime7d         sql.NullInt64   `db:"total_time_7d"`
	ComputedAt          sql.NullString  `db:"computed_at"`
}

type PersonalRecord struct {
	ID              int64           `db:"id"`
	Category        string          `db:"category"`
	ActivityID      int64           `db:"activity_id"`
	DistanceMeters  float64         `db:"distance_meters"`
	DurationSeconds int64           `db:"duration_seconds"`
	PacePerMile     sql.NullFloat64 `db:"pace_per_mile"`
	AvgHeartrate    sql.NullFloat64 `db:"avg_heartrate"`
	AchievedAt      string          `db:"achieved_at"`
	StartOffset     sql.NullInt64   `db:"start_offset"`
	EndOffset       sql.NullInt64   `db:"end_offset"`
}

type RacePrediction struct {
	ID               int64   `db:"id"`
	TargetDistance   string  `db:"target_distance"`
	TargetMeters     float64 `db:"target_meters"`
	PredictedSeconds int64   `db:"predicted_seconds"`
	PredictedPace    float64 `db:"predicted_pace"`
	Vdot             float64 `db:"vdot"`
	SourceCategory   string  `db:"source_category"`
	SourceActivityID int64   `db:"source_activity_id"`
	Confidence       string  `db:"confidence"`
	ConfidenceScore  float64 `db:"confidence_score"`
	ComputedAt       string  `db:"computed_at"`
}

type Stream struct {
	ActivityID     int64           `db:"activity_id"`
	TimeOffset     int64           `db:"time_offset"`
	LatlngLat      sql.NullFloat64 `db:"latlng_lat"`
	LatlngLng      sql.NullFloat64 `db:"latlng_lng"`
	Altitude       sql.NullFloat64 `db:"altitude"`
	VelocitySmooth sql.NullFloat64 `db:"velocity_smooth"`
	Heartrate      sql.NullInt64   `db:"heartrate"`
	Cadence        sql.NullInt64   `db:"cadence"`
	GradeSmooth    sql.NullFloat64 `db:"grade_smooth"`
	Distance       sql.NullFloat64 `db:"distance"`
}

type SyncState struct {
	Key       string         `db:"key"`
	Value     string         `db:"value"`
	UpdatedAt sql.NullString `db:"updated_at"`
}
