// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: personal_records.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deletePersonalRecordsForActivity = `-- name: DeletePersonalRecordsForActivity :exec
DELETE FROM personal_records WHERE activity_id = ?
`

func (q *Queries) DeletePersonalRecordsForActivity(ctx context.Context, activityID int64) error {
	_, err := q.db.ExecContext(ctx, deletePersonalRecordsForActivity, activityID)
	return err
}

const getAllPersonalRecords = `-- name: GetAllPersonalRecords :many
SELECT id, category, activity_id, distance_meters, duration_seconds,
    pace_per_mile, avg_heartrate, achieved_at, start_offset, end_offset
FROM personal_records
ORDER BY category
`

func (q *Queries) GetAllPersonalRecords(ctx context.Context) ([]PersonalRecord, error) {
	rows, err := q.db.QueryContext(ctx, getAllPersonalRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalRecord{}
	for rows.Next() {
		var i PersonalRecord
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.ActivityID,
			&i.DistanceMeters,
			&i.DurationSeconds,
			&i.PacePerMile,
			&i.AvgHeartrate,
			&i.AchievedAt,
			&i.StartOffset,
			&i.EndOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalRecordByCategory = `-- name: GetPersonalRecordByCategory :one
SELECT id, category, activity_id, distance_meters, duration_seconds,
    pace_per_mile, avg_heartrate, achieved_at, start_offset, end_offset
FROM personal_records
WHERE category = ?
`

func (q *Queries) GetPersonalRecordByCategory(ctx context.Context, category string) (PersonalRecord, error) {
	row := q.db.QueryRowContext(ctx, getPersonalRecordByCategory, category)
	var i PersonalRecord
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.ActivityID,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.PacePerMile,
		&i.AvgHeartrate,
		&i.AchievedAt,
		&i.StartOffset,
		&i.EndOffset,
	)
	return i, err
}

const getPersonalRecordsForActivity = `-- name: GetPersonalRecordsForActivity :many
SELECT id, category, activity_id, distance_meters, duration_seconds,
    pace_per_mile, avg_heartrate, achieved_at, start_offset, end_offset
FROM personal_records
WHERE activity_id = ?
ORDER BY category
`

func (q *Queries) GetPersonalRecordsForActivity(ctx context.Context, activityID int64) ([]PersonalRecord, error) {
	rows, err := q.db.QueryContext(ctx, getPersonalRecordsForActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalRecord{}
	for rows.Next() {
		var i PersonalRecord
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.ActivityID,
			&i.DistanceMeters,
			&i.DurationSeconds,
			&i.PacePerMile,
			&i.AvgHeartrate,
			&i.AchievedAt,
			&i.StartOffset,
			&i.EndOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPersonalRecord = `-- name: InsertPersonalRecord :exec
INSERT INTO personal_records (
    category, activity_id, distance_meters, duration_seconds,
    pace_per_mile, avg_heartrate, achieved_at, start_offset, end_offset
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(category) DO UPDATE SET
    activity_id = excluded.activity_id,
    distance_meters = excluded.distance_meters,
    duration_seconds = excluded.duration_seconds,
    pace_per_mile = excluded.pace_per_mile,
    avg_heartrate = excluded.avg_heartrate,
    achieved_at = excluded.achieved_at,
    start_offset = excluded.start_offset,
    end_offset = excluded.end_offset
`

type InsertPersonalRecordParams struct {
	Category        string          `db:"category"`
	ActivityID      int64           `db:"activity_id"`
	DistanceMeters  float64         `db:"distance_meters"`
	DurationSeconds int64           `db:"duration_seconds"`
	PacePerMile     sql.NullFloat64 `db:"pace_per_mile"`
	AvgHeartrate    sql.NullFloat64 `db:"avg_heartrate"`
	AchievedAt      string          `db:"achieved_at"`
	StartOffset     sql.NullInt64   `db:"start_offset"`
	EndOffset       sql.NullInt64   `db:"end_offset"`
}

func (q *Queries) InsertPersonalRecord(ctx context.Context, arg InsertPersonalRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertPersonalRecord,
		arg.Category,
		arg.ActivityID,
		arg.DistanceMeters,
		arg.DurationSeconds,
		arg.PacePerMile,
		arg.AvgHeartrate,
		arg.AchievedAt,
		arg.StartOffset,
		arg.EndOffset,
	)
	return err
}
