// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: streams.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteStreams = `-- name: DeleteStreams :exec
DELETE FROM streams WHERE activity_id = ?
`

func (q *Queries) DeleteStreams(ctx context.Context, activityID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStreams, activityID)
	return err
}

const deleteStreamsForActivity = `-- name: DeleteStreamsForActivity :exec
DELETE FROM streams WHERE activity_id = ?
`

func (q *Queries) DeleteStreamsForActivity(ctx context.Context, activityID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStreamsForActivity, activityID)
	return err
}

const getStreamCount = `-- name: GetStreamCount :one
SELECT COUNT(*) FROM streams WHERE activity_id = ?
`

func (q *Queries) GetStreamCount(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStreamCount, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStreams = `-- name: GetStreams :many
SELECT activity_id, time_offset, latlng_lat, latlng_lng, altitude,
    velocity_smooth, heartrate, cadence, grade_smooth, distance
FROM streams
WHERE activity_id = ?
ORDER BY time_offset
`

func (q *Queries) GetStreams(ctx context.Context, activityID int64) ([]Stream, error) {
	rows, err := q.db.QueryContext(ctx, getStreams, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stream{}
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ActivityID,
			&i.TimeOffset,
			&i.LatlngLat,
			&i.LatlngLng,
			&i.Altitude,
			&i.VelocitySmooth,
			&i.Heartrate,
			&i.Cadence,
			&i.GradeSmooth,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasStreams = `-- name: HasStreams :one
SELECT 1 FROM streams WHERE activity_id = ? LIMIT 1
`

func (q *Queries) HasStreams(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasStreams, activityID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertStreamPoint = `-- name: InsertStreamPoint :exec
INSERT INTO streams (
    activity_id, time_offset, latlng_lat, latlng_lng, altitude,
    velocity_smooth, heartrate, cadence, grade_smooth, distance
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStreamPointParams struct {
	ActivityID     int64           `db:"activity_id"`
	TimeOffset     int64           `db:"time_offset"`
	LatlngLat      sql.NullFloat64 `db:"latlng_lat"`
	LatlngLng      sql.NullFloat64 `db:"latlng_lng"`
	Altitude       sql.NullFloat64 `db:"altitude"`
	VelocitySmooth sql.NullFloat64 `db:"velocity_smooth"`
	Heartrate      sql.NullInt64   `db:"heartrate"`
	Cadence        sql.NullInt64   `db:"cadence"`
	GradeSmooth    sql.NullFloat64 `db:"grade_smooth"`
	Distance       sql.NullFloat64 `db:"distance"`
}

func (q *Queries) InsertStreamPoint(ctx context.Context, arg InsertStreamPointParams) error {
	_, err := q.db.ExecContext(ctx, insertStreamPoint,
		arg.ActivityID,
		arg.TimeOffset,
		arg.LatlngLat,
		arg.LatlngLng,
		arg.Altitude,
		arg.VelocitySmooth,
		arg.Heartrate,
		arg.Cadence,
		arg.GradeSmooth,
		arg.Distance,
	)
	return err
}
