// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sync_state.sql

package sqlc

import (
	"context"
)

const getSyncState = `-- name: GetSyncState :one
SELECT value FROM sync_state WHERE key = ?
`

func (q *Queries) GetSyncState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSyncState = `-- name: SetSyncState :exec
INSERT INTO sync_state (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
`

type SetSyncStateParams struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, setSyncState, arg.Key, arg.Value)
	return err
}
